# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Latvian spellchecker"
lv = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Latvian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
lv = "TRANSLATE: A spellchecker for Latvian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.lv"

[windows]
system_product_code = "{81839789-F873-40EA-B3FB-1BEB48EF45AF}_is1"
legacy_product_codes = [
    { value = "5732C0E0-D957-47A1-9646-66C007458569", kind = "nsis" },
    { value = "64504F22-BEE0-4B38-8EC5-E76D20889832", kind = "nsis" }
]

[package.speller]
name = "Latvian"
version = "0.1.1"

[package.grammar]
name = "Latvian"
version = "0.1.0"

[package.tts-textproc]
name = "Latvian"
version = "0.1.0"

[package.hyphenator]
name = "Latvian"
version = "0.1.0"
