template = "https://github.com/giellalt/template-lang-und"
rev_id = 254
template_sha = "9eb2a95995f59cb63a159a5cc7bcce8f049babe4"

[replacements]
__GLOTTOLOG_ID__ = "latv1249"
__REPO__ = "lang-lav"
__UND2C__ = "lv"
__UNDEFINED__ = "Latvian"
__UND__ = "lav"
